name: js-trions
version: 1.3.0
summary: Easily manage JSON translations in your project.
description: 'Easily manage JSON translations in your project. Should support any framework, programming language.
  
  Use JsTrions to analyze project code for translations usage, you can then easily see which translations are missing and add them.
  
  You can also use automatic translations from one language to other languages.
  
  App works fully offline, so it is not dependant on some online service.
  
  JsTrions works well with Translator provided by my Flutter package tch_appliable_core, but is compatible with any simple json translations.'

confinement: devmode # needs to be script because of flutter
base: core18
grade: stable
issues: https://github.com/tomaschyly/JsTrions/issues
website: https://tomas-chyly.com/en/project/jstrions/

apps:
  js-trions-app:
    command: js-trions-app
    extensions: [flutter-master]

parts:
  js-trions-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
