name: js-trions
version: 1.6.0
summary: Easy to use AI assisted translations of your projects.
description: 'Easy to use AI assisted translations of your projects.

Use JsTrions to analyze project code for translations usage, you can then easily see which translations are missing and add them.

JsTrions works well with Translator provided by my Flutter package tch_appliable_core, but is compatible with any simple json translations.'

confinement: strict
base: core22
grade: stable

icon: snap/gui/js-trions.png
issues: https://github.com/tomaschyly/JsTrions/issues
website: https://tomas-chyly.com/en/project/jstrions/

apps:
  js-trions:
    command: js_trions
    extensions: [gnome]
    plugs:
      - network

parts:
  js-trions:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
